kubesphere/ks-devops

charts/ks-devops/charts/jenkins/templates/home-pvc.yaml
charts/ks-devops/charts/jenkins/values.yaml

Signed-off-by: johnniang <johnniang@fastmail.com>
This pull request is trying to make jenkins use default storage class without specifying its name . For any context details please have a look at the issue below.
Fix #10

Make jenkins use default storage class without specifying its name

---

charts/ks-devops/Chart.yaml

Signed-off-by: johnniang <johnniang@fastmail.com>
Adding missing s2i dependency into ks-devops chart fixes dependencies error while executing `helm lint`.

Add s2i dependency into ks-devops chart

---

pkg/client/k8s/kubernetes.go
pkg/client/k8s/kubernetes_test.go
pkg/kapis/devops/v1alpha3/handler.go

When we request pipeline list api without token as follow.  Http status `Unauthorized` is supposed to be returned, but `Empty reply from server`:
```bash
➜  ~ curl -v http://localhost:9090/kapis/devops.kubesphere.io/v1alpha3/devops/testblpsz/pipelines
*   Trying ::1:9090...
* Connected to localhost (::1) port 9090 (#0)
> GET /kapis/devops.kubesphere.io/v1alpha3/devops/testblpsz/pipelines HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```
This PR tries to fix the following error:
```go
2021/07/06 14:51:45 http: panic serving [::1]:51314: runtime error: invalid memory address or nil pointer dereference
goroutine 649 [running]:
net/http.(*conn).serve.func1(0xc000e5e5a0) …
```

Fix nil error while token is empty

---

charts/ks-devops/charts/jenkins/templates/jenkins-agent-config.yaml

Signed-off-by: johnniang <johnniang@fastmail.com>
When I run a pipeline via ks, and Jenkins dashboard showed as follow:
The reason why the pipeline got stuck in:
```
describe maven-xxxx pod detail:
│ Events:                                                                                                                                                                                                                                                    │
│   Type     Reason       Age                From               Message                                                                                                                                                                                      │
│   ----     ------       ----               ----               ------- …
```

Add worker namespace into ks-devops-agent ConfigMap

---

.github/workflows/build.yaml
charts/ks-devops/values.yaml

- issue: #51 
- Description : 
pointing to container registry **ghcr.io/kubesphere-sigs** instead of **ghcr.io/linuxsuren** in  values.yaml in helm chart
change repository_owner from **kubesphere** to **kubesphere-sigs** in build.yaml
change to docker hub org from **kubespheredev** to **kubespheresig**  in build.yaml

Fix the container namespace from linuxsuren to kubesphere-sigs

---

pkg/apiserver/query/types.go
pkg/apiserver/query/types_test.go
pkg/kapis/devops/v1alpha2/devops.go
pkg/kapis/devops/v1alpha2/devops_test.go
pkg/kapis/devops/v1alpha2/handler.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/models/devops/devops.go
pkg/models/resources/v1alpha3/interface.go
pkg/models/resources/v1alpha3/interface_test.go
pkg/server/params/params.go

This PR is trying to provide more agile filter, sorter for pipeline search api. If do that, we can add more
1. Remove `PipelineFilter` and `PipelineSorter`
2. Use more generic `FilterFunc` and `CompareFunc` instead
3. Add some tests on new mechanism
4. Compatible with previous way of searching pipeline
I've provide more generic way to add filters and sorter for pipeline search api. And I'm going to explain this feature.
Now, we support the following parameters for query:
> See more about [Kubernetes ObjectMeta](https://github.com/kubernetes/apimachinery/blob/a644435e2c133d990b624858d9c01985d7f59adf/pkg/apis/meta/v1/types.go#L116)
- Filters
| Parameter name | Description                         | Filter(contains, match pattern, is)                                             | Example …

Add agile filter, sorter for pipeline search api

---

charts/ks-devops/templates/config.yaml
charts/ks-devops/templates/deployment-apiserver.yaml
charts/ks-devops/values.yaml

If we hard code authentication jwtSecret in helm charts, the jwt tools in init container of ks-devops-apiserver won't update jwt secret correctly, at least we should set the jwt secret with empty. If we integrate with KubeSphere, consistent secrets are required among ks-devops, ks-devops-plugin and KubeSphere, there is no way to set secret in ks-devops and ks-devops-plugin same as KubeSphere.
Extract authentication jwtSecret as a variable. Please refer to #70 for more information.
Fix #70 
/kind bug

Extract authentication jwtSecret as a variable

---

pkg/kapis/devops/v1alpha2/devops.go

I got a nil error when trying to access the Pipeline log output page:
```
2021/07/26 06:13:19 http: panic serving 10.233.115.47:41822: runtime error: invalid memory address or nil pointer dereference
goroutine 892 [running]:
net/http.(*conn).serve.func1(0xc000ae3180)
/usr/local/go/src/net/http/server.go:1795 +0x139
panic(0x1c06000, 0x333f2f0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
kubesphere.io/devops/pkg/kapis/devops/v1alpha2.(*ProjectPipelineHandler).approvableCheck(0xc000a7c180, 0x3388910, 0x0, 0x0, 0x0, 0x0, 0xc0019cb530, 0x9, 0xc0019cb544, 0x4, ...)
/workspace/pkg/kapis/devops/v1alpha2/devops.go:356 +0xf2
kubesphere.io/devops/pkg/kapis/devops/v1alpha2.(*ProjectPipelineHandler).GetNodesDetail(0xc000a7c180, 0xc001561b60, 0xc00039b810) …
```

Fix the userInfo is nil

---

charts/ks-devops/charts/jenkins/README.md
charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
charts/ks-devops/charts/jenkins/values.yaml
charts/ks-devops/charts/s2i/README.md
charts/ks-devops/charts/s2i/templates/_helpers.tpl
charts/ks-devops/charts/s2i/templates/binary.yaml
charts/ks-devops/charts/s2i/templates/java.yaml
charts/ks-devops/charts/s2i/templates/nodejs.yaml
charts/ks-devops/charts/s2i/templates/operator.yaml
charts/ks-devops/charts/s2i/templates/python.yaml
charts/ks-devops/charts/s2i/templates/tomcat.yaml
charts/ks-devops/charts/s2i/values.yaml

Extracting docker registry as one configuration item lets users configure docker image of ks-devops chart easily. Think about if users want to host a private docker registry for docker images related ks-devops.
- Extract agent builder docker registry
- Extract s2i builder docker registry
/kind improvment

Extract agent builder and s2i image's docker registry

---

cmd/controller/app/controllers.go
controllers/jenkinsconfig/jenkinsconfig_controller.go
pkg/client/devops/configuration.go
pkg/client/devops/fake/fakedevops.go
pkg/client/devops/interface.go
pkg/client/devops/jenkins/configuration.go
pkg/client/devops/jenkins/devops.go
pkg/client/devops/jenkins/options.go

Fix #73
Please see #73
- Add `ConfigurationOperator` in DevOps client
- Reload configuration after reconciling Jenkins agent configuration
- Initial http client with no redirection for Jenkins client

Reload Jenkins CasC in Jenkins Config Controller

---

charts/ks-devops/charts/jenkins/templates/jenkins-master-deployment.yaml
charts/ks-devops/charts/jenkins/templates/jenkins-master-statefulset.yaml
charts/ks-devops/charts/jenkins/values.yaml

Fix #45 
description : 
The StatefulSet workload can be enabled by configuring `jenkins.Master.StatefulSet.Enabled`. 
And statefulSet volumeClaimTemplates can be enabled by turning off `jenkins.Persistence.Enable` and configuring `jenkins.Persistence.ExistingClaim`.

Add jenkins workload from statefulSet 

---

charts/ks-devops/charts/jenkins/README.md
charts/ks-devops/charts/jenkins/templates/prometheus-prometheusrule.yaml
charts/ks-devops/charts/jenkins/templates/prometheus-servicemonitor.yaml
charts/ks-devops/charts/jenkins/values.yaml
charts/ks-devops/charts/s2i/README.md
charts/ks-devops/charts/s2i/templates/prometheus-servicemonitor.yaml
charts/ks-devops/charts/s2i/values.yaml

This PR aims to make users use ks-devops metrics out of box or integrate with Prometheus easily.
- Add Prometheus ServiceMonitor and PrometheusRule in Jenkins helm chart
- Add Prometheus ServiceMonitor in S2I helm chart
/kind feature

Add prometheus service monitor and rule

---

pkg/models/devops/devops.go

Clone request in `convertToHttpParameters` method.
Before this, `ks-devops-apiserver` may crash while we view parallel pipeline activity detail. The detailed error stack is showed below:
```go
fatal error: concurrent map writes
goroutine 12555 [running]:
runtime.throw(0x1ee0045, 0x15)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000e6d9d8 sp=0xc000e6d9a8 pc=0x42e542
runtime.mapassign_faststr(0x1cde0e0, 0xc000ba2600, 0x1ed12ad, 0xd, 0x1)
/usr/local/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc000e6da40 sp=0xc000e6d9d8 pc=0x41301e
net/textproto.MIMEHeader.Set(...)
/usr/local/go/src/net/textproto/header.go:22
net/http.Header.Set(...)
/usr/local/go/src/net/http/header.go:37
kubesphere.io/devops/pkg/client/devops/jenkins.(*Jenkins).SendPureRequestWithHeaderResp(0xc00024e990, …
```

Fix ks-devops-apiserver crash while viewing parallel pipeline activity detail

---

.github/workflows/build.yaml

Correct `github.repository_owner` comparison condition from `kubesphere-sigs` into `kubesphere` in GitHub Action configuration.
Please see #113 
Fixes #113

Correct github.repository_owner comparison condition due to org transfer

---

LICENSE

Most of the code lines come from https://github.com/kubesphere/kubesphere/. So it's good to keep to use the same license.

Add license file which is the apache 2.0

---

go.mod
pkg/apiserver/runtime/runtime.go
pkg/apiserver/runtime/runtime_test.go
pkg/kapis/devops/v1alpha2/register.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/models/devops/devops.go

According to the https://github.com/kubesphere/kubesphere/pull/4129. The new DevOps proxy does not send the HTTP request with the group name of DevOps APIs. So in this PR, I let it support two styles that contain or not the group name.
You only need to update the image `surenpi/devops-apiserver:dev--71e1645`. Because this PR didn't change the controller part.
fix #116

Add a root API path which without the group name

---

.github/workflows/build.yaml

Align go version in Test action with version defined in go.mod.
Keep same go version all the time.

Align go version with version defined in go.mod

---

pkg/client/devops/jenkins/credential.go

Fix: #101 
1. Modify the request param to form-data
2. Adjustment request result verification

Fix the API of credential creating/updating failed due to URI is too long

---

.github/workflows/build.yaml

Signed-off-by: GitHub <noreply@github.com>

Make the branch tekton-support can run GitHub actions

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.golangci.yml

1. Extract lint stage
2. Run lint stage on push, pull request and release
3. Increase timeout of golangci
4. Skip cache due to flaky behaviours
There are too many flaky error logs confusing every committer.

Skip golangci-lint cache due to flaky behaviors

---

README.md
charts/ks-devops/crds/devops.kubesphere.io_pipelineruns.yaml
charts/ks-devops/values.yaml
config/crd/bases/devops.kubesphere.io_pipelineruns.yaml

1. Synchronize PipelineRun CRD into chart
2. Change default image registry from ghcr.io/kubesphere-sigs into ghcr.io/kubesphere
The controller refuses to start due to missing PipelineRun CRD which should be installed before start, see logs below:
```go
I0817 11:46:24.860802  523091 server.go:144] setting up manager
I0817 11:46:24.872965  523091 listener.go:44] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"
I0817 11:46:24.873673  523091 server.go:179] Starting cache resource from apiserver...
I0817 11:46:24.873692  523091 server.go:182] Starting the controllers.
I0817 11:46:24.873749  523091 reflector.go:175] Starting reflector *v1alpha1.S2iRun (10m0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I0817 11:46:24.873749  523091 …
```

Fix that devops-ks-devops-controller is always CrashLoopBackOff due to missing PipelineRun CRD

---

pkg/client/devops/jenkins/pure_request.go
pkg/client/devops/jenkins/request.go

Set crumb into request header to Jenkins.
1. Currently, if DevOps part of ks-console want to request some Jenkins resources, like `/kapis/devops.kubesphere.io/v1alpha2/tojson`, it have to request `/kapis/devops.kubesphere.io/v1alpha2/crumbissuer` API in advance. This design is not friendly for front-end. If do that, front-end will no longer care if any API needs to set up crumb.
2. Some reconcilers, like `PipelineReconciler, PipelineRunReconciler`, might request Jenkins APIs. It might be more useful if we  uniformly set up crumb before every request to Jenkins.
Because method `SetCrumbForConsumer` depends on `Requester#GetJSON` method, it's not easy to write a unit test against the method.

Set crumb into request header to Jenkins automatically

---

pkg/client/devops/jenkins/pipeline_internal.go

no description in flow-definition if a Jenkins job was created via JSON API
Please see the file config.xml which was created via JSON API:
```
<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job@2.40">
<keepDependencies>false</keepDependencies>
<properties/>
<triggers/>
<disabled>false</disabled>
</flow-definition>
```
Images:
* `surenpi/devops-apiserver:dev--1376445`
* `surenpi/devops-controller:dev--1376445`

Fix the controller panic due to Jenkins job parse error

---

pkg/client/devops/jenkins/pipeline.go
pkg/models/devops/devops.go

The log output:
Before this PR:
```
E0819 11:29:40.139579       1 pipeline.go:99] invalid character '<' looking for beginning of value
E0819 11:29:40.139598       1 devops.go:405] invalid character '<' looking for beginning of value
E0819 11:29:40.139604       1 devops.go:900] invalid character '<' looking for beginning of value
I0819 11:29:40.139627       1 apiserver.go:613] 10.233.90.68 - "GET /kapis/devops.kubesphere.io/v1alpha2/devops/testnnbnc/pipelines/asdf/ HTTP/1.1" 500 52 60ms
```
Like you can see, the same log was printed three times.

Improve the error message with getting Pipeline

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/init.sh
.gitpod.Dockerfile

You can use the following tools in CodeSpaces:
* ks (with autocompletion support)
* helm
* kubectl
* minikube
Test result:
```
👋 Welcome to Codespaces! You are on a custom image defined in your devcontainer.json file.
🔍 To explore VS Code to its fullest, search using the Command Palette (Cmd/Ctrl + Shift + P)
📝 Edit away, then run your build command to see your code running in the browser.
vscode ➜ /workspaces/ks-devops (add-more-dev-tools) $ ks 
alias       completion  help        option      registry    token       user        
auth        component   install     pipeline    s2i         tool        version     
vscode ➜ /workspaces/ks-devops (add-more-dev-tools) $ ks ^C
vscode ➜ /workspaces/ks-devops (add-more-dev-tools) $ ks get ns
NAME              STATUS   AGE
default …
```

Support to install minikube in CodeSpaces automatically

---

config/samples/devops_v1alpha4_pipelinerun_with_parameters.yaml
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/utils.go
controllers/jenkins/pipelinerun/utils_test.go
go.mod
go.sum

Make parameters in PipelineRunSpec available.
This PR is part of https://github.com/kubesphere/ks-devops/issues/41
Upstream PR: https://github.com/jenkins-zh/jenkins-client/pull/14
/kind feature

Support trigger a parameterized Pipeline in PipelineRun reconciler

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go
pkg/api/devops/v1alpha4/pipelinerun_types.go

Add event recorder into PipelineRun reconciler
Please see https://github.com/kubesphere/ks-devops/pull/210#discussion_r699428922
/kind feature

Add event recorder into PipelineRun reconciler

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go
go.mod
go.sum
pkg/api/devops/v1alpha4/groupversion_info.go

Retrieve PipelineRun stages status and store it into annotations.
This PR is part of https://github.com/kubesphere/ks-devops/issues/41
Upstream PR is https://github.com/jenkins-zh/jenkins-client/pull/19.
/kind feature

Retrieve PipelineRun stages status and store it into annotations

---

.github/workflows/backup.yaml

Sometimes, people will meet the network issues of github.com. Or it might be very slow in some areas of China. But it's very fast to visit https://gitee.com/kubesphere/ks-devops for those users.
Secondly, it's possible to bring some users from https://gitee.com as well.
See also https://gitee.com/kubesphere/ks-devops/commits/master
and the screenshot:

Backup git repo to gitee.com

---

pkg/kapis/devops/v1alpha4/handler.go
pkg/kapis/devops/v1alpha4/register.go

- Provide getting PipelineRun API
This PR is to prepare for PipelineRun feature in APIServer. At the same time, this PR is also a part of #41.
Docker image for test: `johnniang/devops-apiserver:get-pipelinerun`
```bash
curl "http://ip:30880/kapis/devops.kubesphere.io/v1alpha4/namespaces/{namespace}/pipelines/{pipeline}/pipelineruns/{pipelinerun}"
```
```json
{
"kind": "PipelineRun",
"apiVersion": "devops.kubesphere.io/v1alpha4",
"metadata": {
"name": "my-pipeline-runs-jpw4z",
"generateName": "my-pipeline-runs-",
"namespace": "my-second-devops-project97bzf",
"selfLink": "/apis/devops.kubesphere.io/v1alpha4/namespaces/my-second-devops-project97bzf/pipelineruns/my-pipeline-runs-jpw4z",
"uid": "f22420fa-1636-4af7-8654-8df5723b7daa",
"resourceVersion": "6884135",
"generation": 1, …
```

Provide getting PipelineRun API

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go

Add action field into PipelineRunSpec.
We need to be able to control our PipelineRun.

Add action field into PipelineRunSpec

---

config/dockerfiles/tools/Dockerfile

As you can see the size of the new image increased by less than 10M.
```
gitpod /workspaces/ks-devops $ sudo docker images | grep test
test                                             no-ks               9437ba112cb2        54 seconds ago      50.9MB
test                                             with-ks             db392a18a136        2 minutes ago       60.6MB
```
Below is the image base on the new changes: `surenpi/devops-tools:with-ks@sha256:7b69c5801e6b8130eef1f418c1e7358cb26c0fda47494acf579ef52abce866f3`
* Using a download tool
* Using a download tool to download `ks` can be easier to support multiple platform: `arm64` and `amd64`
* Change `ENTRYPOINT` to `CMD`
* There is no server in this image, it's not suitable to set an entrypoint. Set `CMD` is much reasonable. Also, users can …

Put the command line ks into the tools image

---

pkg/kapis/devops/v1alpha2/devops.go
pkg/models/resources/v1alpha3/interface.go
pkg/models/resources/v1alpha3/interface_test.go

Filter nil items in result list
Docker image for test: `johnniang/devops-apiserver:pipeline-search-bug`
/kind bug

Filter nil items in result list

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
CONTRIBUTING.md
config/dockerfiles/apiserver/Dockerfile
config/dockerfiles/controller-manager/Dockerfile
config/dockerfiles/tools/Dockerfile
go.mod
go.sum

Bump go version from 1.13 to 1.16
Some new features of go have been released in go 1.16 and some dependency are using go 1.16, like [jenkins-zh/jenkins-client](https://github.com/jenkins-zh/jenkins-client).
/kind chore

Bump go version from 1.13 to 1.16

---

cmd/controller/app/controllers.go
controllers/devopsproject/devopsproject_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
controllers/jenkins/pipelinerun/utils.go
controllers/jenkins/pipelinerun/utils_test.go
controllers/pipeline/pipeline_controller.go
go.mod
go.sum
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/util.go

Provide Pipeline Synchronizer to synchronize PipelineRun from Jenkins.
After we've done https://github.com/kubesphere/ks-devops/issues/41, we will missing some Jenkins runs which are triggered automatically or old data. So we need a synchronizer to ensure that we can convert them into PipelineRun.
This is the final effect:
Replace the docker image of `devops-apiserver` and `devops-controller` with `johnniang/devops-apiserver:pipelinerun-syncer` and `johnniang/devops-controller:pipelinerun-syncer` respectively.
/kind feature

Provide Pipeline Synchronizer to synchronize PipelineRun from Jenkins

---

Makefile
config/crd/bases/devops.kubesphere.io_devopsprojects.yaml
config/crd/bases/devops.kubesphere.io_fakes.yaml
config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
config/crd/bases/devops.kubesphere.io_s2ibinaries.yaml
config/crd/bases/devops.kubesphere.io_s2ibuilders.yaml
config/crd/bases/devops.kubesphere.io_s2ibuildertemplates.yaml
config/crd/bases/devops.kubesphere.io_s2iruns.yaml
pkg/api/devops/pipelinerun/v1alpha3/pipelinerun_types.go
pkg/api/devops/v1alpha3/pipeline_types.go

It's useful to print some important fields.
Examples:
```
[root@node1 ~]# ks get --all-namespaces pipelinerun
NAMESPACE   NAME         PHASE
testtwsz7   java6bqqt    Failed
[root@node1 ~]# ks get --all-namespaces pipeline
NAMESPACE   NAME   TYPE
testtwsz7   java   pipeline
```

Add additional columns for Pipeline and PipelineRun

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/api/devops/v1alpha3/pipelinerun_types.go

Get pipelines from a shortName:
```shell
➜  ks git:(dashboard) ks get pip --all-namespaces
NAMESPACE         NAME           TYPE                    AGE
godlpfcg          test           pipeline                29h
godlpfcg          gitlab         multi-branch-pipeline   26h
queenglory4zjpr   servantsolar   pipeline                6h42m
```
Get pipelineruns from a shortName:
```shell
➜  ks git:(dashboard) ks get pr --all-namespaces
NAMESPACE         NAME                PHASE       AGE
hellohb82v        craneglowts8xz      Succeeded   46h
godlpfcg          test-g7m8w          Succeeded   29h
hellohb82v        craneglowwv2zx      Succeeded   46h
```
Get pipeline and pipelienruns via category `devops`:
```shell
➜  ks git:(dashboard) ks get devops --all-namespaces
NAMESPACE         NAME …
```

Add shortNames,category for pipeline and pipelinerun

---

.golangci.yml
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
controllers/jenkins/pipelinerun/pipelinerun_finder.go
controllers/jenkins/pipelinerun/pipelinerun_finder_test.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
controllers/jenkins/pipelinerun/utils.go
pkg/api/devops/v1alpha3/groupversion_info.go
pkg/api/devops/v1alpha3/pipelinerun_types.go
pkg/client/devops/jenkins/configuration.go
pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler.go
pkg/kapis/devops/v1alpha3/pipelinerun/backwardlisthandler_test.go
pkg/utils/reflectutils/deep.go

- Enable exported rule of revive for golangci-lint
> Please see https://golangci-lint.run/usage/configuration/#config-file
```yaml
issues:
exclude:
- EXC0012
exclude-use-default: false
```
- Exclude some files by hand
- Add some comment on exported fields, functions and methods according to `golangci-lint`.
> But there is a discussion about the `exported` rule, please see
> - https://github.com/golangci/golangci-lint/issues/456.
> - https://github.com/golangci/golangci-lint/issues/2114#issuecomment-878937553
/kind cleanup

Enable exported rule of revive for golangci-lint

---

cmd/controller/app/controllers.go
controllers/jenkins/pipeline/metadata_converter.go
controllers/jenkins/pipeline/pipeline_metadata_controller.go
go.mod
go.sum
pkg/api/devops/v1alpha3/pipeline_types.go

Provide Pipeline metadata controller to update metadata from Jenkins in every 10 seconds.
And this controller only cares about the newly created Pipelines and the Pipelines that can be obtained when it is restarted.
1. Replace devops controller with docker image `johnniang/devops-controller:dev-v3.2.0-alpha.0-ca751a7`
2. See annotations of Pipeline resources
/kind feature

Provide Pipeline metadata controller to update metadata from Jenkins

---

config/dockerfiles/tools/Dockerfile

See
* https://github.com/kubesphere-sigs/ks/releases
* https://github.com/kubesphere-sigs/ks/pull/219
* https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/24

Bump ks which in the tool image to v0.0.52

---

.github/build-for-e2e/action.yaml
.github/workflows/e2e.install.yaml
test/e2e/cases/chart-install/e2e.yaml
test/e2e/cases/chart-install/expected.yaml
test/e2e/common/kind.yaml

Install helm charts to start ks-devops and validate all Running Pods is running stably.
Last result:
> https://github.com/kubesphere/ks-devops/runs/4149272728?check_suite_focus=true
Fix #342
This PR uses [Apache SkyWalking Infra E2E](https://github.com/apache/skywalking-infra-e2e) to implement our E2E testing.
Learn more from https://skywalking.apache.org/docs/skywalking-infra-e2e/latest/readme/.
/kind feature

Provide basic E2E testing to validate whether it is normal after installing ks-devops

---

.github/workflows/build.yaml
.github/workflows/e2e.install.yaml
.github/workflows/lint.yaml

Configure `paths-ignore` list to disable CI for non-code change according to https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths.
Manual test result:
This would reduce unnecessary workflow runs for non-code change.
Fix #349 
/kind chore

Disable CI for non code change

---

config/dockerfiles/tools/Dockerfile

https://github.com/kubesphere-sigs/ks/pull/241 fixed a potential issue that might cause the token of Jenkins to be empty.
See the release request https://github.com/kubesphere-sigs/ks-versions/pull/10
/kind bug
/label no-changelog

Bump ks cli to version v0.0.58

---

pkg/kapis/devops/v1alpha2/devops.go

Return friendly error if current step is unapprovable.
Please see #366 
#366 
Please replace docker image of `devops-apiserver` deployment with image name below:
```bash
johnniang/devops-apiserver:dev-v3.2.0-43358c2
```
- Create a simple approvable Pipeline and run, which Jenkinsfile is below:
```groovy
pipeline {
agent none
stages {
stage('Input test') {
steps {
input(id: 'deploy-to-prod', message: 'deploy to prod?')
}
}
}
}
```
- Approve the PipelineRun and copy request `http://demo:30880/kapis/devops.kubesphere.io/v1alpha2/devops/test-projectl82l5/pipelines/approable-test/runs/33/nodes/4/steps/5/` as CURL(bash)
- Request the same request again, and you will get the response:
```bash
* upload completely sent off: 23 out of 23 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 …
```

Fix the problem of handling multi submitted input step incorrectly

---

codecov.yml

For many cases, it's hard to add new test coverage. Such as the modification of markdown files. So, we don't need to let the ci to failed.
* https://docs.codecov.com/docs/commit-status#patch-status

Set the threshold of patch to 0% for codecov

---

.github/workflows/build.yaml

/cherrypick release-3.2
This is [the official document](https://github.com/docker/metadata-action#typesemver) which is related to the new changes.

Fix the image tag name from x.x.x to vx.x.x

---

config/dockerfiles/tools/Dockerfile

Bump version of kubephere-sigs/ks tool, from suggestion https://github.com/kubesphere-sigs/ks/pull/245#pullrequestreview-819847883.
Upstream PR: 
- https://github.com/kubesphere-sigs/ks/pull/245
Meanwhile, this PR also needs to wait for next release of https://github.com/kubesphere-sigs/ks.
/kind chore
/hold

Bump up version of kubephere-sigs/ks to v0.0.60

---

controllers/jenkins/pipelinerun/utils.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/listhandler.go
pkg/kapis/devops/v1alpha3/pipelinerun/listhandler_test.go

1. Implement a list handler for PipelineRun
2. Set StartTime status while reconciling PipelineRun
Please see #360 
Fix #360 
Docker images for test:
```bash
johnniang/devops-apiserver:dev-v3.2.1-rc.1-d6e861a
johnniang/devops-controller:dev-v3.2.1-rc.1-d6e861a
```
1. Create a simple Pipeline
2. Trigger it in Jenkins dashboard
3. See "Run Records" in KubeSphere console
/kind bug
/milestone v3.2

Fix messy sequence of PipelineRuns

---

cmd/controller/app/server.go
controllers/jenkins/pipeline/metadata_converter.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
go.mod
go.sum
pkg/api/devops/v1alpha3/groupversion_info.go
pkg/apiserver/apiserver.go
pkg/indexers/indexers.go
pkg/kapis/devops/v1alpha3/pipeline/branch_filter.go
pkg/kapis/devops/v1alpha3/pipeline/branch_filter_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/util.go
pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
pkg/models/pipeline/pipeline.go

- Replace label of SCM ref name with field indexer.
- Remove branch name validation
Please see:
- #104
- #397
Fix #397
Docker images for test:
```bash
johnniang/devops-apiserver:dev-v3.2.1-rc.1-fe5d958
johnniang/devops-controller:dev-v3.2.1-rc.1-fe5d958
```
1. Create Multi-branch Pipeline, using repo <https://gitlab.com/johnniang/jenkinsfile-multi-demo>.
2. Click `Branches` tab and see all branches.
3. Click into branch naming `中文测试分支`
**Please note that KubeSphere console didn't escape the branch name, so we cannot click branch naming `feat/featureA` util console fixes it:**
/kind bug
/cc @kubesphere/sig-devops 
/cc @mangoGoForward

Fix the problem caused by strange branch names that contain special characters

---

pkg/client/devops/pipeline.go
pkg/client/devops/pipeline_test.go
pkg/kapis/devops/v1alpha2/devops.go
pkg/kapis/devops/v1alpha2/devops_test.go

Refine approvable check logic, which `approvableCheck` requires the users who have PipelineRun management permission to approve a PipelineRun. If the particular submitters exist, we also restrict the users who are in the particular submitters.
Since v3.2.0, ks-devops was separated from KubeSphere, which led to a problem that ks-devops could not obtain permissions for currently logging in user, so that we would not determine whether the user has sufficient permission to approve a PipelineRun. So we changed the approvable check logic to adapt the problem.
Please note that our APIs are protected by `ks-apiserver` based on RBAC.
Fixes #407 
Docker image for test:
```bash
johnniang/devops-apiserver:dev-v3.2.1-rc.3-ec505c7
```
1. Create a Workspace, DevOps Project
2. Create two roles for the …

Fix the problem that could not proceed or break the pipeline created by others

---

.github/release-drafter.yml

/kind chore
At present, we are using Prow to collect release notes from pull request, this is why we have pull request #410. 
Then, we don't want to give up using release-drafter, but we have made some efforts on labeling `no-changelog`, please see https://github.com/kubesphere/test-infra/pull/34, but it failed.
At last, I found a label [release-notes-none](https://github.com/kubesphere/ks-devops/labels?q=release) will be labeled if we have no release note in pull request template. So it might be helpful to let release-drafter exclude that label.
Fixes #
```
```
```release-note
None
```

Exclude label release-notes-none for release-drafter

---

cmd/tools/jwt/app/configmap_updater.go
cmd/tools/jwt/app/jwt_root.go
cmd/tools/jwt/app/jwt_root_test.go

/kind feature
Users cannot set a customized token of the Jenkins if there's no the override flag.
Fixes #
You can use the following image to test it.
```
surenpi/devops-tools:dev-v3.2.1-f4b07eb
```
you can add the flag like this: `--override-jenkins-token=false`
```release-note
None
```

Add an override flag to the tool cmd jwt

---

pkg/api/devops/v1alpha3/credential_types.go
pkg/api/devops/v1alpha3/credential_types_test.go
pkg/models/devops/devops.go
pkg/utils/secretutil/secret_mask.go
pkg/utils/secretutil/secret_mask_test.go

/kind bug
/area devops
- Add credential mask;
- Apply the mask into listing, getting, updating and creating credential.
Fixes #299
Docker image for test:
```bash
johnniang/devops-apiserver:dev-v3.2.1-29e5c8b
```
1. Replace the docker image of `devops-apiserver` with test image above;
2. Create a credential for a DevOps Project and see response in browser debug network;
3. Update the credential and see response in browser debug network;
4. Back to credential list and see response in browser debug network;
5. Go into a credential and see response in browser debug network;
```release-note
None
```

Avoid returning secret value of the DevOps credential by creating credential mask

---

pkg/apiserver/filters/requestinfo.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/models/devops/devops.go
pkg/models/devops/devops_test.go

/kind bug
Currently, the UI try to use this API to find if the desired name is duplicated. But for DevOpsProject, we should use the generateName instead of the resource real name.
Fixes #
This PR should be able to fix part of https://github.com/kubesphere/console/issues/2707
```
surenpi/devops-apiserver:dev-v3.2.1-0740803
```
```release-note
Fix the API for getting devops project
```

Fix the API for getting devops project

---

pkg/client/devops/jenkins/request.go
pkg/client/devops/jenkins/request_test.go
pkg/client/devops/jenkins/utils.go
pkg/client/devops/jenkins/utils_test.go

/kind bug
may lead to resource leaks
1.  Using defer in loops
2. call fileData.Close() is too late
Fixes #
```
```
```release-note
None
```
/cc @LinuxSuRen

fix: Using defer in loops and end of loop call fileData.Close() can lead to resource leaks

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/api/devops/v1alpha3/pipeline_types_test.go

/kind bug
Delete PipelineRun not found in Jenkins when synchronizing PipelineRuns.
Fixes #332.
```
Docker image for test: johnniang/devops-controller:dev-v3.2.1-3d87bb3
```
1. Replace docker image of devops-controller deployment
2. Create a simple Pipeline
```groovy
pipeline {
agent none
stages {
stage('Echo') {
steps {
echo "Hello World!"
}
}
}
}
```
3. Run it multiple times
4. Go into Jenkins dashboard
5. Delete any of Jenkins builds
6. Go into KubeSphere DevOps and see PipelineRuns
```release-note
None
```

Delete PipelineRun not found in Jenkins

---

cmd/apiserver/app/options/options.go
controllers/gitrepository/gitrepository_webhook_controller.go
go.mod
go.sum
pkg/apiserver/filters/requestinfo.go
pkg/client/devops/jenkins/pure_request.go
pkg/client/git/client.go
pkg/client/git/client_test.go
pkg/client/git/message.go
pkg/client/git/message_test.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/kapis/devops/v1alpha3/scm/scmhandler.go
pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go
pkg/kapis/devops/v1alpha3/testdata/orgs.json

/kind feature
There are two big reasons why we should have this feature:
* Verify a SCM token has no relationship with Jenkins. So, it is not reasonable to call Jenkins API
* We should avoid use a plain token text as possible as we can
Currently, we use [go-scm](https://github.com/drone/go-scm) which support multiple git providers.
Fixes #
If you want to help to test it, please use the following temporary image:
```
kubespheredev/devops-apiserver:dev-v3.2.1-bdeb73d
```
Below is the test command:
```shell
curl -X POST 'http://ip:30880/kapis/devops.kubesphere.io/v1alpha3/scms/github/verify?secret=github&secretNamespace=default' \
Proxy-C> -H 'Proxy-Connection: keep-alive' \
> -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) …
```

Support to verify SCM token directly instead of call Jenkins API

---

pkg/client/devops/jclient/jenkins.go

/kind bug
If jenkinsCore.GetCrumb() failed, error won't be return and JenkinsClient will be nil. 
This makes program panic and no error message showed up.
https://github.com/kubesphere/ks-devops/blob/6cb96cf0debdc4fc2fcc8af60ab324e5bf6c2102/pkg/client/devops/jclient/jenkins.go#L30-L40
Fixes #
```release-note
None
```
```release-note
```

Fix error handle jclient.NewJenkinsClient()

---

config/dockerfiles/apiserver/Dockerfile
docs/swagger.md
pkg/kapis/doc/registry.go

/kind bug
According to https://github.com/emicklei/go-restful-swagger12#how-to-use-swagger-ui-with-go-restful, I refined the swagger config when registering Swagger service.
```go
config := swagger.Config{
WebServices:    restful.RegisteredWebServices(),
ApiPath:        "/apidocs.json",
SwaggerPath:     "/apidocs/",
SwaggerFilePath: "/Users/emicklei/Projects/swagger-ui/dist"}
swagger.InstallSwaggerService(config)		
```
In `config/apiserver/Dockerfile`, the swagger config is suitable for that, but when we develop in local environment we cannot access the Swagger UI  properly via <http://localhost:9090/apidocs/?url=http://localhost:9090/apidocs.json>.
In this PR, I correct the SwaggerFilePath config and refine `config/apiserver/Dockerfile`. This fix has no impact on how APIServer that are …

Refine Swagger config to access Swagger UI in development environment

---

cmd/controller/app/controllers.go
controllers/argocd/multi-cluster-controller.go
controllers/argocd/multi-cluster-controller_test.go
controllers/argocd/types.go
controllers/argocd/types_test.go

/kind feature
this is part of #63 
With help from this PR, users don't need to add the [ArgoCD cluster](https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_cluster/) manually. They just need to follow [this document](https://kubesphere.com.cn/docs/multicluster-management/introduction/overview/) to add a member cluster, the controller will add the corresponding ArgoCD cluster.
Fixes #
You can use the following image if you want to help to test this PR.
```
surenpi/devops-controller:dev-v3.2.1-50bb80b
```
```release-note
None
```

Support sync kubesphere multi-cluster to argo multi-cluster

---

pkg/kapis/devops/v1alpha1/argocd/handler.go
pkg/kapis/devops/v1alpha1/argocd/route.go
pkg/kapis/devops/v1alpha1/argocd/route_test.go

/kind feature
This is part of #63 
Fixes #
see also #473
Please see the following screenshot of the tests:
```release-note
None
```

Add an API for getting the argo cluster list

---

config/crd/kustomization.yaml

/kind bug
This PR tries to resolve error below when we execute command `make install` or `make uninstall`:
```bash
/home/johnniang/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'bases/devops.kubesphere.io_fakes.yaml': evalsymlink failure on '/home/johnniang/workspaces/kubesphere/ks-devops/config/crd/bases/devops.kubesphere.io_fakes.yaml' : lstat /home/johnniang/workspaces/kubesphere/ks-devops/config/crd/bases/devops.kubesphere.io_fakes.yaml: no such file or directory': evalsymlink failure on '/home/johnniang/workspaces/kubesphere/ks-devops/config/crd/bases/devops.kubesphe …
```

Remove resource config due to non-existing fake CRD

---

cmd/controller/app/server.go
pkg/client/devops/jclient/jenkins.go
pkg/client/devops/jenkins/options.go

/kind feature
In some cases, a developer might only want to test a particular feature instead of the full features. So, it would be better if we can ignore the unnecessary feature.
Fixes #
```release-note
None
```

Add a flag to support skip Jenkins connection in the controller cmd

---

pkg/apis/apis.go

/kind bug
As I mentioned in the title.
The controller will panic if it has the flag `--enabled-controllers argocd=true`.
Fixes #
```release-note
None
```

Fix the missing scheme register for the application

---

config/samples/devops_v1alpha1_application.yaml
pkg/client/git/client.go
pkg/client/git/client_test.go

/kind bug
See the following screenshot:
Currently, this project does not use the original secret type.
Fixes #
this is the upstream of https://github.com/kubesphere/console/pull/2943
```release-note
None
```

Add missing git secret support which belong to ks type

---

config/samples/devops_v1alpha1_clustertemplate.yaml
pkg/kapis/devops/v1alpha3/template/cluster_template_handler.go
pkg/kapis/devops/v1alpha3/template/cluster_template_handler_test.go
pkg/kapis/devops/v1alpha3/template/render.go
pkg/kapis/devops/v1alpha3/template/render_test.go
pkg/kapis/devops/v1alpha3/template/route.go
pkg/kapis/devops/v1alpha3/template/route_test.go
pkg/kapis/devops/v1alpha3/template/template_handler.go
pkg/kapis/devops/v1alpha3/template/template_handler_test.go

/kind feature
Support rendering Template with parameters. So that we could pass parameters to the template render API:
```json
{
"parameters": [
{
"name": "cloneURL",
"value": "https://github.com/halo-dev/halo.git"
},
{
"name": "buildOnly",
"value": "false"
}
]
}
```
Fixes #
About parameters validations and default parametrs, I will handle them in the future.
> Docker image for test: `johnniang/devops-apiserver:dev-v3.2.1-6c40b47`
1. Create a cluster for test
2. Install all CRDs and ClusterTemplate sample
```bash
kubectl apply -f config/crd/bases/
kubectl apply -f config/samples/devops_v1alpha1_clustertemplate.yaml 
```
4. Run DevOps APIServer
5. Try to render the ClusterTemplate sample:
```bash
curl -X POST --header 'Content-Type: application/json' --header 'Accept: …
```

Support rendering Template with parameters

---

pkg/client/devops/jclient/projectPipeline.go
pkg/client/devops/jenkins/pipeline_internal.go

/kind bug
The controller manager panic once there is a multi-branch pipeline.
Fixes #
```release-note
None
```

Fix the multi-branch pipeline creating

---

config/samples/devops_v1alpha1_clustertemplate.yaml
pkg/kapis/devops/v1alpha3/template/render.go
pkg/kapis/devops/v1alpha3/template/render_test.go

/kind feature
As mentioned in the title.
By default, Helm is using go template to render its templates. If we using the same template delimiters as Helm, they will have conflicts. See error below when I tried to add a ClusterTemplate into Helm charts at [here](https://github.com/kubesphere-sigs/ks-devops-helm-chart/pull/62/commits/235e3e1cbaa4e347339ccb7954075e389d3161be):
```bash
helm lint charts/ks-devops
Error: 1 chart(s) linted, 1 chart(s) failed
==> Linting charts/ks-devops
[INFO] Chart.yaml: icon is recommended
Error:  templates/: template: ks-devops/templates/cluster-template-nodejs.yaml:44:[6](https://github.com/kubesphere-sigs/ks-devops-helm-chart/runs/5476016572?check_suite_focus=true#step:4:6)[8](https://github.com/kubesphere-sigs/ks-devops-helm-chart/runs/5476016572?check_suite …
```

Redefine template delimiters to "$( )"

---

controllers/jenkins/pipelinerun/utils.go
controllers/jenkins/pipelinerun/utils_test.go

/kind bug
Always trigger Jenkins Pipeline with non-nil parameters. This will prevent `DevOps Controller` and `Jenkins` with the following errors if we trigger a Pipeline which needs parameters without parameters.
The error in `devops-controller`:
```go
devops-controller-76c4868fb6-567pk E0316 14:30:00.446693       1 pipelinerun_controller.go:184] pipelinerun-controller "msg"="unable to run pipeline" "error"="unexpected status code: 500" "Pipeline"="empty-parameter-demo" "PipelineRun"={"Namespace":"my-devops-projectdq8jj","Name":"empty-parameter-demo-4x75t"} "namespace"="my-devops-projectdq8jj" "pipeline"="empty-parameter-demo"
devops-controller-76c4868fb6-567pk E0316 14:30:00.446798       1 controller.go:246] controller "msg"="Reconciler error" "error"="unexpected status code: 500" …
```

Fix the problem that PipelineRun is always in "Not Running" state

---

cmd/apiserver/app/options/options.go
pkg/client/devops/jclient/jenkins.go
pkg/client/devops/jenkins/devops.go

/kind flake
Please refer to: #496 
https://github.com/kubesphere/ks-devops/blob/14ea1b04b27be835c1d8f399c057fdfb4bb027cc/pkg/client/devops/jclient/jenkins.go#L27-L30
IMO, the structure as a whole should be a `devopsClient.Interface` . this makes it easy to add lines to the API, or to rewrite the old API
```release-note
None
```

Replace it with the new Jenkins client

---

cmd/apiserver/app/options/options.go

/kind feature
Please see the test output with or without the flag:
See also https://github.com/kubesphere/ks-devops/pull/482
Fixes #
```release-note
None
```

Add a flag to ignore the connection faliure of Jenkins

---

go.mod
go.sum
pkg/client/devops/fake/fakedevops.go
pkg/client/devops/jclient/pipeline.go
pkg/client/devops/pipeline.go
pkg/kapis/devops/v1alpha2/devops.go
pkg/kapis/devops/v1alpha2/handler.go
pkg/kapis/devops/v1alpha2/register.go
pkg/kapis/devops/v1alpha2/register_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/register.go
pkg/kapis/devops/v1alpha3/pipelinerun/register_test.go
pkg/kapis/devops/v1alpha3/register.go

/kind feature
Please refer to: https://github.com/kubesphere/ks-devops/issues/449
Fixes #
An API was created in v1aplha2 : https://github.com/mzmuer/ks-devops/blob/bcdd8765ade8743f65de170238f1e989b92c4955/pkg/kapis/devops/v1alpha2/register.go#L668
```release-note
None
```

Create a new API to download artifacts from a PipelineRun

---

config/samples/addon/argocd.yaml
config/samples/addon/argocd_simple_operator.yaml
config/samples/addon/ks_releaser.yaml
config/samples/addon/ks_releaser_simple_operator.yaml
docs/addon.md

See [the upstream PR](https://github.com/kubesphere/ks-devops/pull/495/files#diff-79fcb5a70b9ca0287b27c25750baa58b11e94689aa017be09c355fbb9ae517c0). I have changed the version of CRD `addon`, but forget to change the document as well.
Fixes #
```release-note
None
```

Fix the incorrect version of the addon

---

Makefile
pkg/client/devops/jclient/jenkins.go

/kind bug
The Jenkins client will get the crumb automatically when trying to send a POST request. So, it is totally not necessary to do it at the initial stage.
Fixes #
Please feel free to help me to verify it using the following image:
```
kubespheredev/devops-apiserver:dev-v3.2.1-55c2fe3
```
```release-note
None
```

Avoid getting the Jenkins crumb when creating Jenkins client

---

config/rbac/role.yaml
controllers/addon/addon_controller.go
controllers/argocd/application_controller.go
controllers/argocd/argocd-application-status-controller.go
controllers/jenkins/config/jenkinsconfig_controller.go
controllers/jenkins/devopscredential/devopscredential_controller.go
controllers/jenkins/devopsproject/devopsproject_controller.go
controllers/jenkins/pipeline/pipeline_metadata_controller.go
pkg/kapis/devops/v1alpha2/register.go
pkg/kapis/gitops/v1alpha1/registery.go

/kind chore
As I mentioned in the title. And we should not give too open permission to ks-devops. So, the next step is to change the `cluster-role` of [this file](https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/master/charts/ks-devops/templates/serviceaccount.yaml).
Fixes #
```release-note
None
```

Add missing RBAC permission claim

---

controllers/argocd/application_controller.go
controllers/argocd/argocd-application-status-controller.go
controllers/argocd/argocd-application-status-controller_test.go

/kind bug
Fix an issue where the application status subresource was not updated. 
This issue was produced by https://github.com/kubesphere/ks-devops/pull/506.
Fixes #
```release-note
None
```

Fix an issue where the application status subresource was not updated

---

pkg/kapis/gitops/v1alpha1/argocd/handler.go
pkg/kapis/gitops/v1alpha1/argocd/route.go
pkg/kapis/gitops/v1alpha1/argocd/route_test.go

/kind feature
Provide applications summary API. The request and response look like below:
**Request URL**
```bash
http://localhost:9090/kapis/gitops.kubesphere.io/v1alpha1/namespaces/{namepsace}/applications/-/summary
```
**Response Body**
```json
{
"total": 1,
"healthStatus": {
"Healthy": 1
},
"syncStatus": {
"Synced": 1
}
}
```
Fixes #
```release-note
None
```

Provide applications summary API

---

cmd/apiserver/app/options/options.go
cmd/apiserver/app/server.go
config/rbac/role.yaml
controllers/argocd/application_controller.go
controllers/argocd/application_controller_test.go
controllers/argocd/argocd-application-status-controller.go
controllers/argocd/argocd-application-status-controller_test.go
pkg/api/gitops/v1alpha1/constants.go
pkg/apiserver/apiserver.go
pkg/config/argocd.go
pkg/config/config.go
pkg/kapis/gitops/v1alpha1/argocd/handler.go
pkg/kapis/gitops/v1alpha1/argocd/route.go
pkg/kapis/gitops/v1alpha1/argocd/route_test.go
pkg/kapis/gitops/v1alpha1/registery.go
pkg/utils/k8sutil/objectmeta.go
pkg/utils/k8sutil/objectmeta_test.go

This PR provides a flag to set the namespace of the Argo CD instance: `--argocd-namespace=xxx`. Users need to use this flag if they install Argo CD to other namespaces instead of `argocd`.
Fixes #
```
kubespheredev/devops-apiserver:dev-v3.2.1-48fbb49
```
```
kubespheredev/devops-controller:dev-v3.2.1-48fbb49
```
```release-note
None
```

Provide a flag to set the namespace of the ArgoCD instance

---

pkg/kapis/gitops/v1alpha1/argocd/handler.go

/kind bug
As I mentioned in the title.
Please feel free to use the following image if you want to help to test it:
```
kubespheredev/devops-apiserver:dev-v3.2.1-63a80a0
```
Fixes #
```release-note
None
```

Fix the potential application update conflicts

---

pkg/kapis/devops/v1alpha3/register.go

/kind bug
Please feel free to use the following image if you want to test it:
```
kubespheredev/devops-apiserver:dev-v3.2.1-e166ee9
```
screenshot:
Fixes #
```release-note
None
```

Fix the restful doc of the v1alpha3

---

config/rbac/role.yaml
pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
pkg/kapis/devops/v1alpha3/scm/route.go

/kind bug
Please feel free to use the following image to test it:
```
kubespheredev/devops-apiserver:dev-v3.2.1-61652d9
```
Fixes #
```release-note
None
```

Fix the gitrepository update API cannot change the annotations

---

controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
pkg/kapis/devops/v1alpha3/webhook/register_test.go
pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler.go
pkg/kapis/devops/v1alpha3/webhook/workflowrun_handler_test.go

Fixes #
Please feel free to use the following images to test:
```
kubespheredev/devops-controller:dev-v3.2.1-ce8fbda
```
```
kubespheredev/devops-apiserver:dev-v3.2.1-ce8fbda
```
```release-note
```

Fix the conflicts with duplicated PipelineRuns

---

.github/workflows/lint.yaml

/kind bug
This may resolve the lint errors like below:
The result is as below:
Fixes https://github.com/kubesphere/ks-devops/actions/runs/2114131090
/cc @kubesphere/sig-devops 
```release-note
None
```

Bump golangci lint action to v3

---

cmd/controller/app/controllers.go
controllers/argocd/project_controller.go
controllers/argocd/project_controller_test.go

/kind bug
Fixes #
```release-note
None
```

The AppProject CR should be in the argocd namespace

---

controllers/argocd/application_controller.go
controllers/argocd/application_controller_test.go
pkg/api/gitops/v1alpha1/constants.go
pkg/kapis/gitops/v1alpha1/argocd/handler.go
pkg/kapis/gitops/v1alpha1/argocd/route.go
pkg/kapis/gitops/v1alpha1/argocd/route_test.go

/kind feature
Fixes #
```release-note
None
```

Add Argo CD application cascade deletion support

---

pkg/kapis/gitops/v1alpha1/argocd/handler.go
pkg/kapis/gitops/v1alpha1/argocd/route_test.go

/kind bug
image:
```
kubespheredev/devops-apiserver:dev-v3.3.0-alpha.0-a45dc81
```
Fixes #544
```release-note
None
```

Always return the host cluster info in the cluster list API

---

pkg/models/devops/devops.go

Fixes #
```release-note
None
```

Avoid to return the secret text from API

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
go.mod
go.sum
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/client/clientset/versioned/typed/devops/v1alpha3/pipeline.go

/kind bug
pipeline save will get a error when apiGroup is empty.
https://github.com/kubernetes/kubernetes/issues/79354
Although the comment says it's optional, we'll still get an error if we pass null because there's no omitempty 
```release-note
None
```

fix: ParameterReference apiGroup empty

---

controllers/argocd/multi-cluster-controller.go
controllers/argocd/multi-cluster-controller_test.go
controllers/argocd/types.go
controllers/argocd/types_test.go

/kind bug
As I mentioned in the title.
Fixes #561
```release-note
None
```

Fix the wrong YAML parse of the Argo Cluster

---

cmd/controller/app/controllers.go
cmd/controller/app/options/feature.go
cmd/controller/app/options/feature_test.go
controllers/core/fake.go
controllers/core/named.go
controllers/core/named_test.go
controllers/gitrepository/constants.go
controllers/gitrepository/gitrepository_amend_controller.go
controllers/gitrepository/gitrepository_amend_controller_test.go
controllers/gitrepository/gitrepository_webhook_controller.go
controllers/gitrepository/register.go
controllers/gitrepository/register_test.go
controllers/gitrepository/webhook_notify.go

Fixes #567
```release-note
None
```

Auto amend the Gitlab URL

---

controllers/argocd/application_controller.go
controllers/argocd/application_controller_test.go

/kind bug
Fixes #572
```release-note
None
```

Fix the CD manual sync not work

---

pkg/client/devops/jenkins/pipeline_internal.go
pkg/client/devops/jenkins/pipeline_internal_test.go

/kind bug
Fixes #585
```release-note
None
```

Fix the potential nil panic due to Jenkins job xml parsing

---

cmd/tools/jwt/app/jwt_root.go
cmd/tools/jwt/app/jwt_root_test.go

/kind bug
The secret of JWT might be changed randomly potentially due to the error handling issues.
Fixes #507
```release-note
None
```

Fix the potential jwt secret issues

---

Makefile

Fixes #
```release-note
None
```

Support building image via podman

---

docs/webhook.md
pkg/api/devops/v1alpha3/last_changes.go
pkg/api/devops/v1alpha3/last_changes_test.go
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/api/devops/v1alpha3/pipeline_types_test.go
pkg/apiserver/apiserver.go
pkg/jwt/token/fake_issuer.go
pkg/jwt/token/fake_issuer_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/util.go
pkg/kapis/devops/v1alpha3/pipelinerun/util_test.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/kapis/devops/v1alpha3/webhook/register.go
pkg/kapis/devops/v1alpha3/webhook/register_test.go
pkg/kapis/devops/v1alpha3/webhook/scm.go
pkg/kapis/devops/v1alpha3/webhook/scm_test.go
pkg/models/pipeline/pipeline.go
pkg/models/pipeline/pipeline_test.go

/kind feature
Supported SCM providers:
* GitHub (SaaS)
* Gitlab (SaaS)
* Bitbucket (SaaS)
See the permission part https://github.com/kubesphere/ks-installer/pull/1998
Image of this PR:
```
kubespheredev/devops-apiserver:dev-v3.3.0-alpha.1-d92409f
```
Fixes #
```release-note
Add SCM webhook to trigger Pipelines
```

Add SCM webhook to trigger Pipelines

---

pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go

/kind cleanup
Condition is always 'true' because 'user' is always not 'nil'
Fixes #
None
```release-note
None
```

Condition is always 'true' because 'user' is always not 'nil'

---

pkg/client/devops/jenkins/options.go

/kind bug
You can test this with:
```
ghcr.io/linuxsuren/ks-installer:release-3.3-dev
```
Fixes #
```release-note
None
```

Avoid using the initial Jenkins fake token

---

pkg/kapis/devops/v1alpha3/scm/scmhandler.go
pkg/kapis/devops/v1alpha3/scm/scmhandler_test.go

/kind bug
See the following screenshot with this PR:
Fixes #668
```release-note
None
```

Using a new API to fetch both public and private repos of a user

---

controllers/argocd/application_controller.go
controllers/argocd/application_controller_test.go

/kind feature
Some Argo CD features rely on annotations. For example, the image updater relies on the annotation `argocd-image-updater.argoproj.io/image-list`.
This is part of #676
Please feel free to help us to test it via:
```
ghcr.io/linuxsuren/devops-controller:dev-v3.2.1-6803647
```
Fixes #
```release-note
None
```

Support to copy argocd-related annotations and labels

---

.github/workflows/.trivyignore
.github/workflows/build.yaml

related #725
```release-note
None
```

Skip CVE-2022-1996 for now due to it might cause too many changes

---

cmd/controller/app/controllers.go
controllers/jenkins/pipeline/constants.go
controllers/jenkins/pipeline/interface_test.go
controllers/jenkins/pipeline/json_converter.go
controllers/jenkins/pipeline/json_converter_test.go
controllers/jenkins/pipeline/metadata_converter_test.go
go.mod
go.sum
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/models/devops/devops.go
pkg/models/devops/devops_test.go

Related https://github.com/kubesphere/ks-devops/issues/713
```release-note
None
```

Avoid using Jenkins API to convert Jenkinsfile format

---

pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/models/devops/devops.go

/kind cleanup
Fixes #
```release-note
None
```

Set a generic response for the jenkinsfile update API

---

cmd/controller/app/controllers.go
config/rbac/role.yaml
controllers/fluxcd/git-repository-controller.go
controllers/fluxcd/git-repository-controller_test.go
pkg/api/gitops/v1alpha1/constants.go

/kind feature
/kind design
- Add controllers/fluxcd/git-repository-controller.go for reconciling [source.toolkit.fluxcd.io/v1/beta2/GitRepository](https://github.com/fluxcd/source-controller/blob/812f6e49ddfbe42d5e11da2805b8feb9121cdb88/api/v1beta2/gitrepository_types.go#L273) and devops.kubesphere.io/v1alpha3/GitRepository
- Add controllers/fluxcd/git-repository-controller_test.go for testing the function of the controller
- Add the controller to cmd/controller/app/controllers.go
- Update the config/rbac/role.yaml
Fixes #679 
It has no auth support yet.
None
```release-note
```

Add Git Repository Support for FluxCD

---

cmd/controller/app/controllers.go
controllers/argocd/application_controller_test.go
controllers/argocd/argocd-application-status-controller_test.go
controllers/argocd/git-repository-controller_test.go
controllers/argocd/image-updater-controller_test.go
controllers/argocd/multi-cluster-controller_test.go
controllers/argocd/project_controller_test.go
controllers/core/fake.go
controllers/core/fake_manager.go
controllers/core/fake_manager_test.go
controllers/core/fake_test.go
controllers/jenkins/config/interface_test.go
controllers/jenkins/config/labels_controller.go
controllers/jenkins/config/labels_controller_test.go
go.mod
go.sum
pkg/api/devops/constants.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/handler_test.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/models/devops/common.go
pkg/models/devops/common_test.go
pkg/models/devops/devops.go
pkg/models/devops/devops_test.go
pkg/models/devops/jkerror_test.go
pkg/models/devops/project_credential_handler_test.go
pkg/models/devops/project_pipeline_sonar_handler_test.go
pkg/models/devops/s2ibinary_handler_test.go

/kind feature
As I mentioned in the title.
related #738
```release-note
Support to getting Jenkins agent labels when it's offline
```

Support to get Jenkins agent labels from ConfigMap

---

cmd/controller/app/controllers.go

Signed-off-by: chengleqi <leqicheng@stu.xidian.edu.cn>
/kind cleanup
fix variable typo
None
None
```release-note
```

fix variable typo

---

pkg/client/devops/jenkins/devops_test.go
pkg/client/devops/jenkins/pipeline.go

/kind bug
The cron expression check failed due to Jenkins made some changes.
Fixes #661
```release-note
None
```

Fix the Jenkins cron expression check error

---

.github/workflows/nightly-build.yaml

/kind chore
- Change the destination of nightly-build container images from `ghcr.io/kubesphere` to `ghcr.io/kubesphere-nightly`.
- Remain the `ghcr.io/${{ github.repository_owner }}` destination registry for contributors.
Fixes #419 
Should create **a new repo** and add the **`GHCR_TOKEN_NIGHTLY`** secret.
```release-note
None
```

Update nightly-build workflow

---

config/crd/bases/gitops.kubesphere.io_applications.yaml
pkg/api/gitops/v1alpha1/application.go

/kind bug
It will be a breaking change if the field kind is not optional.
See the following errors:
```
Unprocessable Entity
Application.gitops.kubesphere.io "ks-devops" is invalid: status.kind: Required value
```
/cc @lxm @chengleqi 
Fixes #
```release-note
None
```

Make gitops app kind to be optional

---

cmd/controller/app/controllers.go
config/samples/gitops/fluxcd-application-helmrelease.yaml
config/samples/gitops/fluxcd-application-helmtemplate.yaml
config/samples/gitops/fluxcd-application-kustomization.yaml
controllers/fluxcd/constants.go
controllers/fluxcd/multi-cluster-controller.go
controllers/fluxcd/multi-cluster-controller_test.go

/kind feature
Add **fluxcd/multi-cluster-controller** to sync the _cluster.kubesphere.io/clusters_ and kubeconfig secret which FluxCD Application(_[Kustomization](https://github.com/fluxcd/kustomize-controller/blob/d6688648df46139a97f273138ccd5fc1d69d46b5/api/v1beta2/kustomization_types.go#L67)_ and _[HelmRelease](https://github.com/fluxcd/helm-controller/blob/a2147639031eb1362360b52c6f596c066270ecc4/api/v2beta1/helmrelease_types.go#L84)_) needs for Multi-Cluster Management. 
Fixes #767 
```release-note
None
```

Add Multi-Cluster Management for Flux Application

---

cmd/controller/app/controllers.go
cmd/controller/app/options/feature.go
cmd/controller/app/options/feature_test.go
controllers/gitrepository/pull_request_status_controller.go

/kind feature
Fixes #
```release-note
None
```

Support to set the cluster name

---

.golangci.yml
docs/permission.md

Fixes #
```release-note
None
```

Doc: allow authenticated users checking Pipeline running log

---

docs/webhook.md
pkg/kapis/devops/v1alpha3/webhook/scm.go

Fixes #
```release-note
None
```

Fix the webhook settings doc errors

---

controllers/fluxcd/application-controller.go
controllers/fluxcd/application-controller_test.go

/kind bug
We should provide the nil pointer check and set a default value (10m0s) to the HelmChart's Interval field.
Fixes #
```release-note
None
```

Fix nil pointer issue when building helmchart

---

pkg/client/devops/jenkins/jenkins.go

Signed-off-by: zhangjiahua <1430635185@qq.com>
Close #822 
/kind bug
fix jenkins connection hang if set maxconnction zero
Fixes #822 
/assign @linuxsuren
No
```release-note
```

fix(api/jenkins): fix jenkins connection hang if set maxconnction zero

---

Makefile
cmd/controller/app/options/feature.go
cmd/controller/app/options/feature_test.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go
pkg/store/configmap/pipelinerun.go
pkg/store/configmap/pipelinerun_test.go
pkg/store/fake/fake_core_test.go
pkg/store/fake/fake_store.go
pkg/store/store/types.go
pkg/store/store/types_test.go

/kind feature
Fixes #
```release-note
Support to store PipelineRun data into ConfigMap
```

Support to store PipelineRun data into ConfigMap

---

cmd/controller/app/controllers.go
controllers/fluxcd/constants.go
controllers/fluxcd/fluxcd-application-status-controller.go
controllers/fluxcd/fluxcd-application-status-controller_test.go
pkg/external/fluxcd/helm/v2beta1/condition_types.go
pkg/external/fluxcd/kustomize/v1beta2/condition_types.go
pkg/external/fluxcd/meta/conditions.go

/kind feature
/kind design
Watch HelmRelease and Kustomization to Update the FluxApp's status.
Add labels to the Application like below:
```
gitops.kubepshere.io/type=HelmRelease
gitops.kubesphere.io/sync-status=Synced
gitops.kubesphere.io/synced-number=1
```
So we can track App's status in the frontend like this:
Fixes #
```release-note
None
```

Add Status for FluxApp

---

controllers/fluxcd/multi-cluster-controller.go

/kind design
I want to add `/clusters` API for fluxcd but the old label is too general. It may get more clusters than expect.
Fixes #
```release-note
None
```

Change cluster secret label

---

cmd/apiserver/app/server.go
pkg/config/config.go

/kind cleanup
I want to add flux config flag to make the apiserver dynamic register the route by the `fluxcd` or `argocd` flag. And I found this.
Fixes #
```release-note
None
```

clean-up: Move ArgoCDOption into apiserverconfig

---

controllers/jenkins/pipeline/pipeline_metadata_controller.go

/kind bug
Fixes https://github.com/kubesphere/ks-devops/issues/836
```release-note
```

Trigger pipeline metadata controller reconsile when update pipeline cr spec

---

controllers/jenkins/pipelinerun/utils.go

Fixes #859
```release-note
Inprove pipelinerun lifecycle，remove confused queued stage.
```

Remove queued status for pipelinerun #859

---

controllers/jenkins/pipelinerun/utils_test.go

fix test for remove queue status

---

config/dockerfiles/tools/Dockerfile

Add one of the following kinds:
/kind bug
Optionally add one or more of the following kinds if applicable:
/kind flake
upgrade ks-tools 
Fixes  part of #847 
```
DevOps will clean-up the pipelinerun that outdated of configuration in "Build Settings"
```

update ks-tool to 0.0.70

---

controllers/gitrepository/pull_request_status_controller.go

/kind bug
Fix bug of nil pointer of pipelinerun.Status.CompletionTime when pipelinerun doesn't complete.
Fixes #811 
```release-note
None
```

bugfix: nil pointer of CompletionTime

---

Makefile
cmd/controller/app/controllers.go
cmd/controller/app/options/feature.go
cmd/controller/app/options/feature_test.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler_test.go
pkg/store/configmap/pipelinerun.go
pkg/store/configmap/pipelinerun_test.go
pkg/store/fake/fake_core_test.go
pkg/store/fake/fake_store.go
pkg/store/store/types.go
pkg/store/store/types_test.go

Fixes #
```release-note
Support to store PipelineRun data into ConfigMap
```

Support to store PipelineRun data into ConfigMap (#825)

---

.github/workflows/latest-build.yaml

Fixes #
```release-note
none
```

change user for ghcr to kubesphere

---

pkg/client/devops/jclient/projectPipeline.go
pkg/client/devops/jenkins/constants.go
pkg/client/devops/jenkins/pipeline_internal.go
pkg/client/devops/jenkins/project_pipeline.go
pkg/client/devops/jenkins/triggers/genericwebhook.go

/kind bug
fix bug of the some jenkins configxml overwrite by pipelienrun-controller.
Fixes https://github.com/kubesphere/kubesphere/issues/5193
```release-note
support updatePipelinerunConfigXml in pipelinerun-controller
```

Bugfix ks 5193

---

controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
pkg/client/devops/jenkins/triggers/genericwebhook.go

/kind failing-test
Fixes #
```release-note
None
```

update test func: storePipelineRunData

---

.github/workflows/check.yaml

/kind chore
Fixes #
```release-note
None
```

add check: lint and unit-test for PR

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
controllers/jenkins/pipelinerun/pipelinerun_controller.go
pkg/api/devops/v1alpha3/pipelinerun_types.go

/kind bug
Fixes #864 
```release-note
bugfix: the status of pipelinerun change to not running after cancel it
add printer-column(ID) of pipelinerun for kubectl
```

bugfix: the status of pipelinerun change to not running after cancel it

---

controllers/jenkins/pipeline/json_converter.go
controllers/jenkins/pipeline/json_converter_test.go
controllers/jenkins/pipeline/pipeline_controller.go
controllers/jenkins/pipeline/pipeline_metadata_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
pkg/api/devops/v1alpha3/pipeline_types.go

/kind bug
Now front end get jenkinsfile from annotations.pipeline.devops.kubesphere.io/jenkinsfile in pipeline cr.
Old created pipelines, there are not such annotations, ui will not show.
Fixes #714
```release-note
auto sync jenkinsfile for pre version pipeline
```

Auto sync jenkinsfile for pre version pipeline

---

config/rbac/role.yaml
controllers/jenkins/pipeline/json_converter.go

Fixes #908
```release-note
none
```

Fix reconcile json edit mode

---

.github/workflows/e2e.install.yaml
config/rbac/role.yaml
controllers/jenkins/config/jenkinsconfig_controller.go
pkg/models/devops/devops.go
test/e2e/common/kind-1.23.yaml

Fixes part of #865 
support: filter pipeline by type in ListPipelineObj
```release-note
none
```

Add type filter for pipeline

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go
go.mod
go.sum

fix bug that pipelinerun deleted by controller
/kind bug
Fixes #920 
```release-note
pipelinerun deleted by controller if get build failed with error
```

Bugfix 920 pipelinerun deleted - merge to master

---

cmd/tools/app/init_config.go
cmd/tools/app/root.go
cmd/tools/jwt/app/agent.go

/kind bug
Fixes #
```release-note
none
```

bugfix: get password from kubesphere-config error in init-container

---

pkg/kapis/gitops/v1alpha1/argocd/route_test.go
pkg/kapis/gitops/v1alpha1/gitops/handler.go

Fixes https://github.com/kubesphere/issues/issues/1052
```release-note
Fix the issue of removing argocd resources without cascade parameter
```

Fix the issue of removing argocd resources without cascade parameter

---

pkg/client/devops/fake/fakedevops.go
pkg/client/devops/jclient/pipeline.go
pkg/client/devops/jenkins/jenkins.go
pkg/client/devops/jenkins/pipeline.go
pkg/client/devops/pipeline.go
pkg/client/devops/project.go
pkg/kapis/devops/v1alpha2/devops.go
pkg/kapis/devops/v1alpha2/register.go
pkg/kapis/devops/v1alpha2/register_test.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/models/devops/devops.go
pkg/models/devops/devops_test.go

Fixes #https://github.com/kubesphere/issues/issues/971
```release-note
add apis to check if the name of DevOps-Project or Pipeline exist
```

Bugfix 971 add check job name api

---

pkg/client/devops/fake/fakedevops.go
pkg/client/devops/jclient/pipeline.go
pkg/client/devops/jenkins/jenkins.go
pkg/client/devops/pipeline.go
pkg/kapis/devops/v1alpha2/devops.go
pkg/kapis/devops/v1alpha2/register.go
pkg/kapis/devops/v1alpha2/register_test.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/models/devops/devops.go

Fixes #https://github.com/kubesphere/issues/issues/971
```release-note
none
```

change checkPipelineName and checkDevopsName apis

---

pkg/kapis/devops/v1alpha3/handler.go

Fixes #
```release-note
change fmt.Errorf to errors.NewBadRequest
```

change fmt.Errorf to errors.NewBadRequest

---

go.mod
go.sum
pkg/api/devops/v1alpha3/pipelinerun_types.go
pkg/api/devops/v1alpha3/pipelinerun_types_test.go
pkg/client/devops/fake/fakedevops.go
pkg/client/devops/fake/fakedevops_test.go
pkg/client/devops/jclient/pipeline.go
pkg/client/devops/pipeline.go
pkg/kapis/devops/v1alpha3/pipelinerun/handler.go

/kind bug
Multi-branch pipeline artifacts download failed
jenkins-client pr: https://github.com/jenkins-zh/jenkins-client/pull/64
Fixes #https://github.com/kubesphere/kubesphere/issues/5821
None
```release-note
fixed the bug with downloading multi-branch-pipeline artifacts
```

fix: Solve the problem of failure to download multi-branch-pipeline artifacts

---

pkg/client/devops/jenkins/internal/gitlab.go

/kind bug
Fixes #873 
```release-note
fix panic when timeout is nil in gitlab cloneOptions
```

fix panic when timeout is nil in gitlab cloneOptions

---

pkg/kapis/devops/v1alpha3/handler.go

/kind bug
Fixes #
```release-note
None
```

fix: scan branch failed when source type is gitsource

---

pkg/client/devops/jenkins/internal/bitbucket.go
pkg/client/devops/jenkins/internal/git.go
pkg/client/devops/jenkins/internal/github.go
pkg/client/devops/jenkins/internal/gitlab.go
pkg/client/devops/jenkins/internal/scm.go
pkg/kapis/imagebuilder/v1alpha1/handler.go

/kind bug
Fixes #873 
```release-note
solve controller start error when timeout in CloneOptionTrait is nil
```

solve controller start error when timeout in CloneOptionTrait is nil

---

controllers/argocd/multi-cluster-controller.go
controllers/argocd/types.go
controllers/argocd/types_test.go

Fixes #
```release-note
Fix nil in log
```

Fix nil in log

---

controllers/jenkins/devopscredential/devopscredential_controller.go
controllers/jenkins/devopsproject/devopsproject_controller.go

remove devops namespace's ownerreferences checking/settings. 
Fixes https://github.com/kubesphere/project/issues/5991
```release-note
remove devops namespace's ownerreferences checking and settings
```

remove devops namespace ownerreferences

---

controllers/argocd/multi-cluster-controller.go
controllers/argocd/multi-cluster-controller_test.go
controllers/fluxcd/multi-cluster-controller.go
controllers/fluxcd/multi-cluster-controller_test.go

allow deploy application on host cluster
Fixes https://github.com/kubesphere/project/issues/6084
```release-note
Fix argocd cluster controller
```

fix argocd controller

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go

/kind bug
Fixes #https://github.com/kubesphere/project/issues/5519
```release-note
none
```

fix: pod name couldn't be empty

---

.github/workflows/build.yaml
pkg/api/devops/v1alpha3/credential_types.go
pkg/client/devops/credential.go
pkg/client/devops/jclient/credential.go
pkg/client/devops/jclient/credential_test.go
pkg/client/devops/jclient/jenkins.go
pkg/client/devops/jenkins/options.go
pkg/client/devops/util/credential.go

the kubeconfigContent credential is deprecated because the provider https://github.com/jenkinsci/kubernetes-cd-plugin has been suspended, should use secret-text to store kubeconfig in the future.
Fixes https://github.com/kubesphere/project/issues/6185
```release-note
support multiple kubeconfig saving types
```

support kubeconfig saving type

---

pkg/constants/constants.go
pkg/kapis/devops/v1alpha3/gitops/factory.go
pkg/kapis/devops/v1alpha3/scm/scmhandler.go

/kind feature
Fixes # https://github.com/kubesphere/project/issues/6609
```release-note
support self-signed certificates & skip tls authentication
```

support self-signed certificates & skip tls authentication
