kubesphere/ks-devops

charts/ks-devops/crds/devops.kubesphere.io_devopsprojects.yaml
charts/ks-devops/crds/devops.kubesphere.io_pipelines.yaml

Signed-off-by: johnniang <johnniang@fastmail.com>
Follow this instruction: <https://helm.sh/docs/chart_best_practices/custom_resource_definitions/> for working with CRD.

Move crd files into crds folder

---

Makefile
README.md
charts/ks-devops/charts/jenkins/templates/NOTES.txt
charts/ks-devops/charts/jenkins/templates/_helpers.tpl
charts/ks-devops/charts/jenkins/templates/config.yaml
charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
charts/ks-devops/charts/jenkins/templates/jenkins-master-deployment.yaml
charts/ks-devops/charts/jenkins/templates/secret.yaml
charts/ks-devops/charts/jenkins/values.yaml
charts/ks-devops/templates/NOTES.txt
charts/ks-devops/templates/deployment-controller.yaml
charts/ks-devops/values.yaml
controllers/devopsproject/devopsproject_controller.go

There're three changes you can find in this PR:
* provide a constant password for the admin user
* make the default security realm be local instead of LDAP
* we will support OIDC later
* provide a correct server address for the KubeSphere token server

Fix the communication issue between ks-devops and Jenkins

---

README.md

Added communication channels to the README file #47

Add  DevOps team contact in the README

---

pkg/apiserver/apiserver.go
pkg/apiserver/authentication/authenticators/bearertoken/bearertoken.go
pkg/apiserver/authentication/token/jwt.go
pkg/apiserver/authentication/token/jwt_test.go
pkg/apiserver/filters/requestinfo.go
pkg/kapis/devops/v1alpha2/handler.go
pkg/kapis/devops/v1alpha3/handler.go

1. Install KubeSphere with [branch remove-devops-ctrl](https://github.com/LinuxSuRen/kubesphere/tree/remove-devops-ctrl)
2. Install ks-devops, then update the image`surenpi/devops-apiserver:dev--43c24d5`
3. Install https://github.com/kubesphere-sigs/ks-devops-plugin

Fix the token verify error

---

README.md

**issue:** #48
**description :** include ks-devops postman team link in the readme file

Create a team in postman for ks-devops

---

README.md
charts/ks-devops/templates/deployment-apiserver.yaml
charts/ks-devops/templates/deployment-controller.yaml
charts/ks-devops/values.yaml

Change the default registry to multiple registries (#61)

---

README.md

Fix #68
description : update description in the README file for the the implement #56

update readme for Fix the token verify error 

---

.github/workflows/build.yaml
README.md
charts/ks-devops/values.yaml

Change the docker hub org from kubespheresig to kubespheredev

---

README.md

Signed-off-by: rick <LinuxSuRen@users.noreply.github.com>

Correct the GitHub org in the README file

---

.devcontainer/devcontainer.json

GitHub codespaces will read config files from .devcontainer

Add devcontainer config file

---

.github/workflows/build.yaml

* branch [tekton-support](https://github.com/kubesphere/ks-devops/tree/tekton-support) is for the support of Tekton
* branch [jenkins-client-refactor](https://github.com/kubesphere/ks-devops/tree/jenkins-client-refactor) is for the Jenkins client refactor
the prefix feat/ represent a long term feature branch
the prefix fix/ represents a long term bugfix branch

Add more feature branches

---

controllers/jenkinsconfig/README.md

See the details from the README file.

Add the desgin document of Jenkins config controller

---

README.md
docs/projects.md

fix: #50 
description:
Adding a collection of kubesphere DevOps related projects to doc

Add a collection of DevOps related projects

---

README.md

* Adding go report card and contributors badge
* Removed the license scanning part due to KubeSphere GitHub does not adopt that

Add some badges into readme file

---

Makefile
charts/ks-devops/README.md
charts/ks-devops/charts/jenkins/README.md
charts/ks-devops/charts/jenkins/templates/_helpers.tpl
charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml
charts/ks-devops/charts/jenkins/values.yaml

This is part of https://github.com/kubesphere/ks-devops/issues/67
You can get details from README file.

Add podman support in the Jenkins chart

---

docs/tekton-support.md

Add documentation for Tekton support including usage , design and implementation details

Add documentation for Tekton support

---

README.md

- refine DevOps installation guide
- reformat README.md

Refine DevOps installation guide

---

config/samples/devops_v1alpha4_pipelinerun_multi_branch_demo.yaml
controllers/jenkins/pipelinerun/pipelinerun_controller.go
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go
go.mod
go.sum
pkg/api/devops/v1alpha4/pipelinerun_types.go
pkg/api/devops/v1alpha4/pipelinerun_types_test.go

- Support multi-branch pipeline build and fetching build
This PR is part of #41
Upstream PR is https://github.com/jenkins-zh/jenkins-client/pull/16.
```bash
kubectl apply -f config/samples/devops_v1alpha4_pipelinerun_multi_branch_demo.yaml
watch kubectl -n demo-devopsproject get pipelinerun demo-pipelinerun -o yaml
```
/kind feature

Support multi-branch pipeline build and fetching build

---

.github/workflows/nightly-build.yaml

This is part of #216 
See the images:
* https://github.com/linuxsuren/ks-devops/pkgs/container/devops-controller/versions
* https://github.com/linuxsuren/ks-devops/pkgs/container/devops-apiserver/versions
* https://github.com/linuxsuren/ks-devops/pkgs/container/devops-tools/versions

Add a new GitHub action to create nightly build

---

CONTRIBUTING.md
README.md
docs/README.md
docs/cli.md
docs/installation.md
docs/projects.md

fix https://github.com/kubesphere/ks-devops/issues/211
This PR can explain itself due to it is documentation contribution.
* I changed some files which you might be interested in them
* @JohnNiang @AbdelouahabMbarki @shihh
* I'm trying to fix an issue created by you
* @FeynmanZhou

Provide more guide document for the potential contributors

---

go.mod
go.sum

Bump version of jenkins-zh/jenkins-client.
Please see https://github.com/jenkins-zh/jenkins-client/pull/21

Bump version of jenkins-zh/jenkins-client

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/api/devops/v1alpha3/pipelinerun_types.go

Please see the following screenshots:

Support print the age of pipeline and pipelinerun

---

controllers/jenkins/pipelinerun/pipelinerun_finder.go
controllers/jenkins/pipelinerun/pipelinerun_finder_test.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer.go
controllers/jenkins/pipelinerun/pipelinerun_synchronizer_test.go
pkg/kapis/devops/v1alpha3/pipelinerun/util.go

- Add PipelineRun identity and finder to filter PipelineRun
- Refine PipelineRun creation function
- Fix #257
- Fix #260
Docker image for test: `johnniang/devops-controller:sync-pr-with-multi-branch`

Synchronize PipelineRun for multi branch pipeline

---

.gitpod.yml

Avoid interactive during the gh repo fork

---

README.md

Signed-off-by: Felixnoo <felixliu@kubesphere.io>
@LinuxSuRen @JohnNiang 
Hi, I made minor updates to `README.md`. Please take a look, thanks.

Minor Updates in README.md

---

.github/build-for-e2e/action.yaml
.github/e2e/action.yaml
.github/workflows/e2e.install.yaml
test/e2e/cases/chart-install/e2e.yaml
test/e2e/common/kind-1.19.yaml
test/e2e/common/kind-1.20.yaml
test/e2e/common/kind-1.21.yaml
test/e2e/common/kind-1.22.yaml

Provide Kubernetes matrix E2E testing.
Please see #347.
Fix #347
Upstream PR: #343 
/kind feature

Provide Kubernetes matrix E2E testing

---

docs/README.md
docs/e2e.md

Provide E2E testing documentation.
Please see #350.
Fix #350.

Provide E2E testing documentation

---

pkg/kapis/devops/v1alpha3/handler.go

reuse  handler devopsProject to devops. and queryParam to query

[Codebase improvement] Reuse handlers devopsProject to devops

---

pkg/client/devops/jenkins/internal/bitbucket.go
pkg/client/devops/jenkins/internal/github.go
pkg/client/devops/jenkins/internal/gitlab.go
pkg/client/devops/jenkins/pipeline_internal_test.go

Due to this fixing being too minor, I prefer to don't put this into the changelog.

Fix the potential panic with git multi-branch source XML parse

---

controllers/jenkins/pipeline/metadata_converter.go
controllers/jenkins/pipeline/metadata_converter_test.go
go.mod
go.sum
pkg/client/devops/jenkins/constants.go

1. Bump Jenkins client;
2. Simplify type of parameter definition.
Please see #365 
Fix #365 
Docker image for test: `johnniang/devops-controller:dev-v3.2.0-4fce6cf`
Upstream PR: 
- https://github.com/jenkins-zh/jenkins-client/pull/39
/kind bug

Fix the problem of rendering choice parameter incorrectly

---

.github/workflows/build.yaml

See this issue about the usage of raw https://github.com/docker/metadata-action/issues/154
See the official document https://github.com/docker/metadata-action#typesemver

Always add the prefix v into the image tag name

---

.github/workflows/build.yaml

/kind bug
Correct semver pattern config for docker meta action. Or it will output tags like below:
```json
{
"tags": [
"kubespheredev/devops-controller:vpattern",
"kubespheredev/devops-controller:sha-bf62a65",
"kubespheredev/devops-controller:latest",
"ghcr.io/kubesphere/devops-controller:vpattern",
"ghcr.io/kubesphere/devops-controller:sha-bf62a65",
"ghcr.io/kubesphere/devops-controller:latest"
]
}
```
The problem was caused by #403, and this PR tries to fix it.
```
```
```release-note
None
```
/cc @kubesphere/sig-devops 
/cherry-pick release-3.2

Correct semver pattern config for docker meta action

---

controllers/jenkins/pipelinerun/jenkins_handler.go
controllers/jenkins/pipelinerun/jenkins_handler_test.go

/kind bug
As I mentioned in the PR title.
Fixes #417
If you want to help to test with the temporary image, please try this one
```
surenpi/devops-controller:dev-v3.2.1-d2faf87@sha256:5d2a8c661d06c911f729dd8f6b87f8463a164a8fbbd191aba2f8b11605e75883
```
```release-note
Fix the multi-branch PipelineRun cannot be deleted
```

Fix the multi-branch PipelineRun cannot be deleted

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Issue templates can help contributors to file an issue in a better format. You can see the screenshot below:
Fixes #
Inspire from [halo](https://github.com/halo-dev/halo/tree/master/.github/ISSUE_TEMPLATE).
```release-note
None
```

Add two issue templates, bug report and feature request

---

config/rbac/role.yaml
controllers/jenkins/devopsproject/devopsproject_controller.go

/kind chore
It is pretty clear. Just see the PR title.
Fixes #
```
```
```release-note
None
```

Add missing rbac annotation of the devopsProject controller

---

pkg/kapis/devops/v1alpha1/argocd/handler.go
pkg/kapis/devops/v1alpha1/argocd/handler_test.go
pkg/kapis/devops/v1alpha1/argocd/route.go
pkg/kapis/devops/v1alpha1/argocd/route_test.go
pkg/kapis/devops/v1alpha1/common/options.go
pkg/kapis/devops/v1alpha1/register.go
pkg/kapis/devops/v1alpha1/template/handler.go
pkg/kapis/devops/v1alpha1/template/handler_test.go
pkg/kapis/devops/v1alpha1/template/route.go

/kind feature
This is part of #63 
Fixes #
```
None
```
```release-note
None
```

Add API for the application custom resource

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

/kind chore
Having a check list be able to avoid missing some necessary work.
Fixes #
```
```
```release-note
None
```

Add a check list into the pull request template

---

pkg/kapis/devops/v1alpha3/template/render.go

/kind feature
Refine error tips when rendering template and log the error details.
Fixes #
```release-note
None
```

Refine error tips when rendering template

---

config/rbac/role.yaml
pkg/kapis/devops/v1alpha3/register.go

As I mentioned in the title. This is similar to #505
Fixes #
```release-note
None
```

Add missing rabc of the devopsproject

---

pkg/apiserver/query/types.go
pkg/kapis/common/options.go
pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
pkg/kapis/devops/v1alpha3/scm/route.go
pkg/kapis/devops/v1alpha3/scm/types.go
pkg/kapis/gitops/v1alpha1/argocd/route.go

Fixes #
```
kubespheredev/devops-apiserver:dev-v3.2.1-1e9f69d
```
```release-note
None
```

Support list the git repository list with paging

---

controllers/argocd/application_controller.go

/kind bug
Fixes #
```release-note
None
```

Fix the potential duplicated Argo Apps

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
go.mod
go.sum
pkg/api/devops/v1alpha3/pipeline_types.go
pkg/kapis/devops/v1alpha3/handler.go
pkg/kapis/devops/v1alpha3/pipeline/handler.go
pkg/kapis/devops/v1alpha3/register.go
pkg/kapis/devops/v1alpha3/register_test.go
pkg/models/devops/devops.go
pkg/models/devops/devops_test.go

Signed-off-by: lxm <lxm.xupt@gmail.com>
/kind feature
fix #523 
```release-note
Support dynamic parameters for Pipelines with ConfigMap
```

Support dynamic parameters with configmap data

---

config/crd/bases/devops.kubesphere.io_pipelineruns.yaml
config/crd/bases/devops.kubesphere.io_pipelines.yaml
pkg/api/devops/v1alpha3/pipeline_types.go

Signed-off-by: lxm <lxm.xupt@gmail.com>
/kind bug
fix isQuoted optional
```release-note
None
```

Dynamic parameters: fix isQuoted optional

---

go.mod
go.sum

Signed-off-by: lxm <lxm.xupt@gmail.com>
/kind bug
```release-note
Fix: CVE-2022-27191
```

Fix CVE-2022-27191

---

cmd/controller/app/controllers.go

/kind cleanup
remove unused method parameters
Fixes #
/cc @kubesphere/sig-devops 
None
```release-note
None
```

remove unused method parameters

---

docs/faq.md

Fixes #
```release-note
None
```

Create a FAQ document

---

docs/customize-pipeline-steps.md

Read the details in the document.
see #602
```release-note
Support pipeline step template
```

Add a draft desgin of the pipeline steps

---

docs/testing.md

See the details in the document.
Fixes #
```release-note
None
```

Provide a document for the pressure testing

---

.github/workflows/api-testing.yaml
.gitignore
Makefile
config/crd/kustomization.yaml
config/default/kustomization.yaml
config/manager/apiserver-service.yaml
config/manager/apiserver.yaml
config/manager/config.yaml
config/manager/kustomization.yaml
config/manager/nameReference.yaml
config/rbac/auth_proxy_client_clusterrole.yaml
test/api/data/devops_v1alpha3_steptemplate.yaml
test/api/testcase-1.yaml
test/api/testcase-2.yaml
test/api/testcase-render.yaml

/kind test
Fixes #
```release-note
None
```

Support to do the API testing

---

Makefile
cmd/tools/tpl/README.md
cmd/tools/tpl/render.go
cmd/tools/tpl/root.go
pkg/api/devops/v1alpha3/steptemplate_render.go
pkg/api/devops/v1alpha3/steptemplate_render_test.go
pkg/api/devops/v1alpha3/steptemplate_types.go
pkg/kapis/devops/v1alpha3/steptemplate/handler.go
pkg/kapis/devops/v1alpha3/steptemplate/route_test.go

/kind feature
Fixes #
```release-note
None
```

Support to render step templates via CLI

---

controllers/jenkins/config/README.md

/kind chore
just fix a typo
Fixes #
```release-note
None
```

typo fix: annotation->annotations

---

docs/image-automation.md

Fixes #
```release-note
None
```

Provide a documentation of the image updater

---

docs/README.md
docs/permission.md

Fixes #
```release-note
None
```

Add a document about the API permission

---

controllers/fluxcd/git-repository-controller_test.go

Signed-off-by: chengleqi <leqicheng@stu.xidian.edu.cn>
/kind cleanup
Add unit test case for flux/git-repository-controller
None
```release-note
None
```

Add unit test case for flux/git-repository-controller

---

config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
pkg/api/devops/v1alpha3/steptemplate_types.go

Fixes #
```release-note
None
```

Add a field to indicate desired agent

---

config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
pkg/api/devops/v1alpha3/steptemplate_types.go

Fixes #
```release-note
None
```

Add a condition field to the step template

---

cmd/tools/tpl/render.go
codecov.yml
pkg/api/devops/v1alpha3/steptemplate_render.go
pkg/api/devops/v1alpha3/steptemplate_render_test.go
pkg/api/devops/v1alpha3/testdata/docker-login.json
pkg/jwt/token/jwt.go
pkg/jwt/token/jwt_test.go
pkg/kapis/devops/v1alpha3/steptemplate/handler.go

/kind chore
Fixes #
```release-note
None
```

Support object in the step paramters

---

Makefile

/kind chore
Shoud change rbac:roleName from `manager-role` to `ks-devops` either.
None
```release-note
None
```

chore: Update Makefile

---

.golangci.yml

/kind chore
Fixes #
```release-note
None
```

Disable lint rule package-comments

---

go.mod
go.sum
pkg/client/devops/jclient/credential.go
pkg/client/devops/jclient/credential_test.go

/kind bug
It fix the bug that issue #809 metioned.
Fixes #809 
```release-note
None
```

Fix error sync credential

---

.github/Jenkinsfile
controllers/gitrepository/gitrepository_webhook_controller.go
controllers/gitrepository/pull_request_status_controller.go
controllers/gitrepository/pull_request_status_controller_test.go
controllers/gitrepository/testdata/statuses.json
pkg/utils/stringutils/error.go
pkg/utils/stringutils/error_test.go

/kind bug
Fixes #
```release-note
None
```

Avoid pipeline running status order override

---

docs/projects.md

Fixes #
```release-note
None
```

Organize all devops related projects into a table

---

docs/gc.md

Fixes #
```release-note
None
```

doc: pipelinerun GC description

---

controllers/jenkins/pipelinerun/utils_test.go

same as: https://github.com/kubesphere/ks-devops/pull/868

fix test for remove queue status

---

cmd/controller/app/controllers.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go

fix https://github.com/kubesphere/ks-devops/pull/825
same as: https://github.com/kubesphere/ks-devops/pull/855
pr to master branch
```release-note
Support to store PipelineRun data into ConfigMap
```

Assign pipelinerun data store to reconsiler

---

.github/workflows/latest-build.yaml

Signed-off-by: pixiake <guofeng@yunify.com>
/kind cleanup
add latest build action
Fixes #
```release-note
none
```

add latest build action

---

.github/workflows/latest-build.yaml
controllers/jenkins/pipelinerun/pipelinerun_controller_test.go

Fixes #
```release-note
none
```

Fix test & Fix action

---

.github/workflows/latest-build.yaml

Fixes #
```release-note
none
```

change latest-build github action, use github.ref_name tag

---

.github/workflows/latest-build.yaml

Fixes #
```release-note
none
```

add latest build action, same as: #879

---

.github/workflows/latest-build.yaml

Fixes #
```release-note
none
```

fix latest-build action skopeo cmd

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go

/kind bug
save pipelinerun stage data to configmap
Fixes #853
```release-note
save pipelinerun result to annotation
```

update: save pipelinerun result to annotation

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go

/kind bug
save pipelienrun stage data to configmap
Fixes #
```release-note
update: save pipelinerun result to annotation
```

update: save pipelinerun result to annotation (#885)

---

pkg/client/devops/jclient/projectPipeline.go
pkg/client/devops/jenkins/constants.go
pkg/client/devops/jenkins/pipeline_internal.go
pkg/client/devops/jenkins/project_pipeline.go
pkg/client/devops/jenkins/triggers/genericwebhook.go

/kind bug
fix bug of the some jenkins configxml overwrite by pipelienrun-controller.
```release-note
support updatePipelinerunConfigXml in pipelinerun-controller
```

 bugfix ks 5193

---

controllers/jenkins/pipelinerun/pipelinerun_controller.go

Fixes #905 
```release-note
Add retry when update pipelinerun annotation
```

add retry for pipelinerun annotation update

---

cmd/tools/app/init_config.go
cmd/tools/app/root.go
cmd/tools/app/tool_root.go
cmd/tools/app/utils.go
cmd/tools/jwt/app/agent.go
cmd/tools/main.go
config/dockerfiles/tools/Dockerfile
go.mod
pkg/client/devops/jenkins/options.go

/kind bug
Fixes #924 
```release-note
fix the bug that pipelinerun not run created by a new user
```

Bugfix 924 token inconsistent

---

controllers/jenkins/pipeline/json_converter.go

/kind bug
Fixes #930 
```release-note
none
```

retry to validate if connection error

---

config/crd/bases/devops.kubesphere.io_clustersteptemplates.yaml
config/crd/bases/devops.kubesphere.io_gitrepositories.yaml
pkg/api/devops/v1alpha3/gitrepository.go
pkg/api/devops/v1alpha3/steptemplate_types.go

/kind feature
Fixes https://github.com/kubesphere/issues/issues/985
```release-note
re-use the code-repos in step-template
```

re-use the code-repos in step-template

---

pkg/client/devops/jenkins/pipeline_internal.go

/kind bug
Fixes #970 
```release-note
fix that disable discarded history pipelineruns doesn't work
```

disable discarded history pipelineruns doesn't work

---

config/dockerfiles/tools/Dockerfile

Fixes #982
```release-note
fix bug of GC pipelineruns
```

upgrade ks: fix bug of gc pipelineruns

---

controllers/jenkins/pipeline/json_converter.go
pkg/api/devops/v1alpha3/steptemplate_render.go
pkg/api/devops/v1alpha3/steptemplate_render_test.go

Fixes #
```release-note
Fix shell validate error
```
fix #1000

Fix shell validate failed

---

cmd/apiserver/app/options/options.go
cmd/controller/app/options/options.go
docs/swagger.md
pkg/config/gitops.go
pkg/kapis/doc/registry.go

Fixes #1008
```release-note
None
```

update swagger info for SwaggerUI

---

pkg/client/devops/jenkins/pipeline_internal.go

/kind bug
Fixes #1018
```release-note
fix the bug that disable delete branchs not works
```

set pruneDeadBranches to false when without discarder

---

cmd/controller/app/controllers.go
controllers/jenkins/pipelinerun/pipelinerun_controller.go
pkg/api/devops/v1alpha3/groupversion_info.go

/kind feature
Fixes #https://github.com/kubesphere/project/issues/5519
```release-note
none
```

update agent info to annotation

---

.gitignore
pkg/client/git/client.go
pkg/kapis/devops/v1alpha3/scm/gitrepository_handler.go
pkg/kapis/devops/v1alpha3/scm/scmhandler.go
pkg/kapis/devops/v1alpha3/scm/utils.go

/kind feature
Fixes #https://github.com/kubesphere/project/issues/5457
```release-note
add git repository reachability validation
```

add git repository reachability validation

---

pkg/client/sonarqube/interface.go

fix SonarAdditionalFields
Fixes https://github.com/kubesphere/project/issues/6550
```release-note
fix SonarAdditionalFields
```

fix sonarqube client

---

controllers/argocd/git-repository-controller.go

/kind bug
update agocd repo skip tls verify
Fixes # https://github.com/kubesphere/project/issues/6609
```release-note
none
```
doc: https://argo-cd.readthedocs.io/en/latest/operator-manual/argocd-repositories-yaml/

update agocd repo skip tls verify
